fork = false
frame = "none"
idle = true
maximized = false
no-multigrid = false
srgb = false
tabs = true
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["JetBrainsMono Nerd Font Mono"]
size = 17
hinting = "full"
edging = "antialias"
